name: Volatility Check Cron

on:
  schedule:
    - cron: "0 0,3,4,6,7,9,10,12,13,15,16,18,19,21,22 * * *"  
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: |
          curl -X GET \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          https://eth-alert.vercel.app/api/cron/job
